project:
  type: website

website:
  title: "GSoC2024"
  site-url: "https://fnhirwa.github.io/GSoC2024"
  description: "GSoC2024 project for sktime"
  page-navigation: true
  output-dir: docs
  navbar:
    search: false
    left:
      - href: docs/examples.ipynb
        text: Notebooks Examples
    right:
      - href: https://fnhirwa.github.io
        text: About Me
      - icon: github
        href: https://github.com/fnhirwa
      - icon: twitter-x
        href: https://x.com/fnhirwa
      - icon: linkedin
        href: https://www.linkedin.com/in/fnhirwa
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



